# Generated by Django 4.2.4 on 2023-08-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employers',
            name='focal_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employers',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employers',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
