# Generated by Django 4.2.4 on 2023-08-28 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nextacloudapp', '0003_brands_items_staff_store_delete_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_manager', to='nextacloudapp.staff'),
        ),
    ]
